export const metadata = {
  title: "Gallery — Dominat8.io",
  description: "Websites generated by AI in seconds. Real examples from Dominat8.",
};

const EXAMPLES = [
  { prompt: "A luxury plumbing company in Auckland — premium, trustworthy, modern", industry: "Construction", grad: "linear-gradient(135deg,#1a0a2e,#2d1654,#0a1628)", accent: "#7C5CFF" },
  { prompt: "A boutique coffee roastery in Brooklyn with a subscription service", industry: "Restaurant", grad: "linear-gradient(135deg,#1a0800,#3d1a08,#2a1200)", accent: "#C09A5C" },
  { prompt: "A personal injury law firm that wins cases and takes no prisoners", industry: "Law Firm", grad: "linear-gradient(135deg,#0a0f1a,#0f1e38,#152244)", accent: "#4A90E2" },
  { prompt: "A cutting-edge SaaS tool that automates customer support with AI", industry: "SaaS", grad: "linear-gradient(135deg,#050814,#0a1030,#061224)", accent: "#3DF0FF" },
  { prompt: "A high-end wedding photography studio in Melbourne", industry: "Portfolio", grad: "linear-gradient(135deg,#140808,#2a1010,#1a0c0c)", accent: "#FF4D6D" },
  { prompt: "A fitness studio in Manhattan specialising in reformer Pilates", industry: "Fitness", grad: "linear-gradient(135deg,#080808,#141414,#101010)", accent: "#38F8A6" },
  { prompt: "An artisan bakery in Paris offering bespoke wedding cakes", industry: "Restaurant", grad: "linear-gradient(135deg,#1a1008,#2d1e0a,#1a1208)", accent: "#FFD166" },
  { prompt: "A luxury real estate agency on the Gold Coast of Australia", industry: "Real Estate", grad: "linear-gradient(135deg,#0a0a08,#1a1808,#141200)", accent: "#C9A84C" },
  { prompt: "A telemedicine platform connecting patients with specialists", industry: "Medical", grad: "linear-gradient(135deg,#040d14,#081a26,#061018)", accent: "#38C9A4" },
  { prompt: "A sustainable architecture firm specialising in net-zero residential builds", industry: "Construction", grad: "linear-gradient(135deg,#081408,#102210,#0a1a0a)", accent: "#76E87A" },
  { prompt: "A venture capital firm focused on climate tech and deep science", industry: "Business", grad: "linear-gradient(135deg,#0c0c14,#141428,#0c0c1e)", accent: "#9B7FD4" },
  { prompt: "A luxury day spa and wellness retreat in Queenstown, NZ", industry: "Hospitality", grad: "linear-gradient(135deg,#14080e,#280e1a,#1a0a12)", accent: "#FFB5C8" },
  { prompt: "A cybersecurity startup protecting enterprises from AI-powered threats", industry: "Technology", grad: "linear-gradient(135deg,#040810,#080f20,#040c18)", accent: "#00E5FF" },
  { prompt: "A premium online education platform for executive leadership skills", industry: "Education", grad: "linear-gradient(135deg,#0e0a04,#201408,#180e04)", accent: "#F0924A" },
  { prompt: "A luxury safari and wildlife photography tour operator in Kenya", industry: "Travel", grad: "linear-gradient(135deg,#100c04,#201808,#180e04)", accent: "#D4A843" },
  { prompt: "A family-owned vineyard and cellar door in Marlborough, NZ", industry: "Hospitality", grad: "linear-gradient(135deg,#140a14,#281428,#1e101e)", accent: "#C078D4" },
  { prompt: "A D2C skincare brand using AI to personalise routines", industry: "E-commerce", grad: "linear-gradient(135deg,#0e0e14,#1a1a28,#121220)", accent: "#E8ACFF" },
  { prompt: "A global recruitment agency placing C-suite executives", industry: "Business", grad: "linear-gradient(135deg,#080c10,#101820,#0c1418)", accent: "#4A90E2" },
];

export default function GalleryPage() {
  return (
    <main style={{
      minHeight: "100vh",
      background: "#06080e",
      color: "#e9eef7",
      fontFamily: "ui-sans-serif,system-ui,-apple-system,sans-serif",
      padding: "0 0 80px",
    }}>
      {/* Nav */}
      <nav style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "18px 32px", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
        <a href="/" style={{ display: "flex", alignItems: "center", gap: 8, textDecoration: "none", color: "inherit" }}>
          <span style={{ fontSize: 17, fontWeight: 800, letterSpacing: "-0.04em" }}>D8</span>
          <span style={{ width: 5, height: 5, borderRadius: "50%", background: "rgba(61,240,255,0.7)", display: "inline-block" }} />
          <span style={{ fontSize: 13, fontWeight: 500, color: "rgba(255,255,255,0.45)" }}>Dominat8.io</span>
        </a>
        <div style={{ display: "flex", gap: 8 }}>
          <a href="/templates" style={{ padding: "8px 18px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.10)", background: "rgba(255,255,255,0.03)", color: "rgba(255,255,255,0.60)", textDecoration: "none", fontSize: 13 }}>Templates</a>
          <a href="/pricing" style={{ padding: "8px 18px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.10)", background: "rgba(255,255,255,0.03)", color: "rgba(255,255,255,0.60)", textDecoration: "none", fontSize: 13 }}>Pricing</a>
          <a href="/" style={{ padding: "8px 18px", borderRadius: 999, background: "linear-gradient(135deg,#00C97A,#00B36B)", color: "#fff", textDecoration: "none", fontSize: 13, fontWeight: 600 }}>Start building →</a>
        </div>
      </nav>

      {/* Hero */}
      <div style={{ textAlign: "center", padding: "56px 24px 40px" }}>
        <div style={{ display: "inline-block", padding: "4px 14px", borderRadius: 999, border: "1px solid rgba(61,240,255,0.25)", background: "rgba(61,240,255,0.06)", color: "rgba(61,240,255,0.85)", fontSize: 12, fontWeight: 600, letterSpacing: "0.06em", marginBottom: 20 }}>
          GALLERY
        </div>
        <h1 style={{ fontSize: "clamp(32px,5vw,52px)", fontWeight: 800, margin: "0 0 14px", letterSpacing: "-0.04em", lineHeight: 1.05 }}>
          Websites built by AI.<br />In seconds.
        </h1>
        <p style={{ fontSize: 16, color: "rgba(255,255,255,0.42)", margin: 0, lineHeight: 1.6, maxWidth: 480, marginLeft: "auto", marginRight: "auto" }}>
          Every site below was generated from a single text prompt. Click any card to try that prompt yourself.
        </p>
      </div>

      {/* Grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 16, maxWidth: 1200, margin: "0 auto", padding: "0 24px" }}>
        {EXAMPLES.map((ex, i) => (
          <a
            key={i}
            href={`/?prompt=${encodeURIComponent(ex.prompt)}`}
            style={{
              borderRadius: 18,
              border: "1px solid rgba(255,255,255,0.08)",
              overflow: "hidden",
              textDecoration: "none",
              color: "inherit",
              display: "block",
              transition: "transform 200ms ease, border-color 200ms ease",
              background: ex.grad,
            }}
            onMouseEnter={e => { (e.currentTarget as HTMLElement).style.transform = "translateY(-4px)"; (e.currentTarget as HTMLElement).style.borderColor = "rgba(255,255,255,0.18)"; }}
            onMouseLeave={e => { (e.currentTarget as HTMLElement).style.transform = "translateY(0)"; (e.currentTarget as HTMLElement).style.borderColor = "rgba(255,255,255,0.08)"; }}
          >
            {/* Preview mockup */}
            <div style={{ height: 180, position: "relative", overflow: "hidden", padding: 16, display: "flex", flexDirection: "column", gap: 10 }}>
              {/* Simulated nav */}
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "6px 10px", borderRadius: 8, background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.08)" }}>
                <div style={{ width: 40, height: 6, borderRadius: 3, background: ex.accent, opacity: 0.8 }} />
                <div style={{ display: "flex", gap: 6 }}>
                  {[0,1,2].map(j => <div key={j} style={{ width: 22, height: 4, borderRadius: 2, background: "rgba(255,255,255,0.20)" }} />)}
                </div>
              </div>
              {/* Simulated hero */}
              <div style={{ flex: 1, borderRadius: 8, background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.06)", padding: "12px 14px", display: "flex", flexDirection: "column", justifyContent: "flex-end", gap: 6 }}>
                <div style={{ width: "75%", height: 8, borderRadius: 4, background: "rgba(255,255,255,0.55)" }} />
                <div style={{ width: "55%", height: 5, borderRadius: 3, background: "rgba(255,255,255,0.25)" }} />
                <div style={{ display: "flex", gap: 6, marginTop: 4 }}>
                  <div style={{ width: 52, height: 16, borderRadius: 4, background: ex.accent }} />
                  <div style={{ width: 44, height: 16, borderRadius: 4, background: "rgba(255,255,255,0.10)", border: "1px solid rgba(255,255,255,0.15)" }} />
                </div>
              </div>
              {/* Try prompt badge */}
              <div style={{ position: "absolute", top: 12, right: 12, padding: "3px 8px", borderRadius: 999, background: "rgba(0,0,0,0.5)", border: "1px solid rgba(255,255,255,0.12)", fontSize: 10, color: "rgba(255,255,255,0.55)", backdropFilter: "blur(6px)" }}>
                Try this →
              </div>
            </div>

            {/* Meta */}
            <div style={{ padding: "12px 16px 14px", borderTop: "1px solid rgba(255,255,255,0.06)" }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 6 }}>
                <span style={{ fontSize: 11, padding: "2px 8px", borderRadius: 999, background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.10)", color: "rgba(255,255,255,0.55)" }}>{ex.industry}</span>
                <span style={{ fontSize: 11, color: "rgba(255,255,255,0.30)" }}>AI generated</span>
              </div>
              <p style={{ margin: 0, fontSize: 12, color: "rgba(255,255,255,0.65)", lineHeight: 1.5, display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" }}>
                {ex.prompt}
              </p>
            </div>
          </a>
        ))}
      </div>

      {/* CTA */}
      <div style={{ textAlign: "center", padding: "56px 24px 0" }}>
        <h2 style={{ fontSize: 28, fontWeight: 700, letterSpacing: "-0.03em", margin: "0 0 12px" }}>Ready to build yours?</h2>
        <p style={{ fontSize: 15, color: "rgba(255,255,255,0.45)", margin: "0 0 24px" }}>It takes 30 seconds. No account required.</p>
        <a href="/" style={{ display: "inline-block", padding: "14px 32px", borderRadius: 14, background: "linear-gradient(135deg,#00C97A,#00B36B)", color: "#fff", textDecoration: "none", fontSize: 15, fontWeight: 700, boxShadow: "0 4px 20px rgba(0,201,122,0.40)", letterSpacing: "-0.01em" }}>
          Start building for free →
        </a>
      </div>

      <style>{`
        @media (max-width: 900px) {
          div[style*="gridTemplateColumns: repeat(3"] { grid-template-columns: 1fr 1fr !important; }
        }
        @media (max-width: 560px) {
          div[style*="gridTemplateColumns: repeat(3"] { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </main>
  );
}
