// AUTO-GENERATED by D8_IO_ONE_SHOT_OVERNIGHT_AGENT_001.ps1
// Default TV route -> tv-glass (temporary default)
// NOTE: This is a routing-only change; no visible UI redesign.

import { redirect } from "next/navigation";

export default function TVDefault() {
  redirect("/tv-glass");
}